[package]
name = "structpack"
version = "0.1.0"
authors = ["dolson"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
gimli = "0.16.1"
object = "0.11.0"
failure = "0.1.5"
clap = "2.32.0"

[profile.release]
debug = true

